# Generated by Django 5.2.7 on 2025-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receiver_email',
            field=models.EmailField(default='abdulla@example.com', max_length=254),
        ),
    ]
