# Generated by Django 5.2.7 on 2025-11-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_company_options_shipment_receiver_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
