# Generated by Django 5.2.7 on 2026-02-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_company_is_active_company_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
